model:
  name: two_view_pipeline
  extractor:
    name: extractors.joint_point_line_extractor
    line_df_decoder_channels: 64
    training:
      do: False
    max_num_keypoints: 2048
    line_detection:
        do: True
        conf:
          lsd_type: old
          sigma: 0.9
    checkpoint: assets/jpl_best.tar
  matcher:
    name: matchers.line_matcher
benchmarks:
  megadepth1500:
    data:
      preprocessing:
        side: long
        resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
  hpatches:
    data:
      preprocessing:
        side: long
        resize: 800
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 1024
    use_points: False
    use_lines: True
  hpatches_lines:
    data:
      preprocessing:
        side: long
        resize: 800
