model:
  name: two_view_pipeline
  extractor:
    name: gluefactory.models.extractors.mixed
    interpolate_descriptors_from: all_descriptors
    detector:
      name: gluefactory.models.extractors.pl_net_extractor
      max_num_junctions: 1000
      num_keypoints: 1000
    descriptor:
      name: gluefactory.models.extractors.superpoint
      max_num_keypoints: 0 # set to only return dense descriptors
      sparse_outputs: false
  matcher:
    name: matchers.nearest_neighbor_matcher
benchmarks:
  megadepth1500:
    data:
      preprocessing:
        side: long
        resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
      options:
        min_iterations: 2000
        max_iterations: 2000000
    model:
      extractor:
        detector:
          max_num_junctions: 2048
          num_keypoints: 2048
  megadepth1500_extended:
    data:
      preprocessing:
        side: long
        resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
      options:
        min_iterations: 2000
        max_iterations: 2000000
    model:
      extractor:
        detector:
          max_num_junctions: 2048
          num_keypoints: 2048
  hpatches:
    data:
      preprocessing:
        side: long
        resize: 800
    eval:
      estimator: poselib
      ransac_th: -1
      options:
        min_iterations: 2000
        max_iterations: 2000000
    model:
      extractor:
        detector:
          max_num_junctions: 1024
          num_keypoints: 1024
  hpatches_extended:
    data:
      preprocessing:
        side: long
        resize: 800
    eval:
      estimator: poselib
      ransac_th: -1
      options:
        min_iterations: 2000
        max_iterations: 2000000
    model:
      extractor:
        detector:
          max_num_junctions: 1024
          num_keypoints: 1024
  scannet1500:
    data:
      preprocessing:
        side: long
        resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
      options:
        min_iterations: 2000
        max_iterations: 2000000
    model:
      extractor:
        detector:
          max_num_junctions: 2048
          num_keypoints: 2048
