model:
    name: two_view_pipeline
    extractor:
        name: extractors.ripe
        top_k: 2048
        threshold: 1.0
        force_num_keypoints: False
        trainable: False
    matcher:
        name: matchers.nearest_neighbor_matcher
benchmarks:
    megadepth1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: poselib
            ransac_th: 0.5
    scannet1500:
        data:
            preprocessing:
                side: long
                resize: 1600
        eval:
            estimator: poselib
            ransac_th: 0.5
        model:
            extractor:
                top_k: 2048
    hpatches:
        eval:
            estimator: poselib
            ransac_th: 0.5
        model:
            extractor:
                top_k: 1024
