model:
  name: two_view_pipeline
  extractor:
    name: lines.wireframe_suarez
  matcher:
    name: matchers.line_matcher
    line_dist: orth
benchmarks:
  hpatches_lines:
    data:
      preprocessing:
        side: long
        resize: 800