model:  # TODO: REPLACE MODEL WITH YOU MODEL CFG YOU WANT TO BENCHMARK
  name: two_view_pipeline
  extractor:
    name: extractors.joint_point_line_extractor
    max_num_keypoints: 2048  # setting for training, for eval: -1
    detection_threshold: 0.0 # set to <= 0 for training, for eval without fixed num of kp, do set to a good value
    nms_radius: 3
    subpixel_refinement: True
    line_df_decoder_channels: 64
    training:
      do: False
    timeit: False  # override timeit: False from BaseModel
    line_detection:
        do: True
        conf:
          faster_lsd: False
    checkpoint: null
  matcher:
    # select matcher needed for the benchmark - ex matchers.nearest_neighbor_matcher for point benchmarks
    name: matchers.line_matcher
benchmarks:
  megadepth1500:
    data:
      preprocessing:
        side: long
        resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 2048
  megadepth1500_extended:
    data:
      preprocessing:
        side: long
        resize: 1600
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 2048
  hpatches:
    data:
      preprocessing:
        side: long
        resize: 800
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 1024
  hpatches_extended:
    data:
      preprocessing:
        side: long
        resize: 800
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 1024
  hpatches_lines:
    data:
      preprocessing:
        side: long
        resize: 800
    eval:
      estimator: poselib
      ransac_th: -1
    model:
      extractor:
        max_num_keypoints: 1024
